// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCCnjgAy6Hum148BNrRBtb0MID4AlrOlU',
    appId: '1:932125453091:web:69d39caa4788b5bf083a96',
    messagingSenderId: '932125453091',
    projectId: 'social-app-with-firebase-63a46',
    authDomain: 'social-app-with-firebase-63a46.firebaseapp.com',
    storageBucket: 'social-app-with-firebase-63a46.appspot.com',
    measurementId: 'G-8WTE1WS524',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvPI5ITmXfZrNgALGuNJHxprwjJfgmteE',
    appId: '1:932125453091:android:0594c245b64ad04e083a96',
    messagingSenderId: '932125453091',
    projectId: 'social-app-with-firebase-63a46',
    storageBucket: 'social-app-with-firebase-63a46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMjF2-Ahr0HQudFDjTDhxZVQP51dELX_0',
    appId: '1:932125453091:ios:ee392c6ccaaf4c1e083a96',
    messagingSenderId: '932125453091',
    projectId: 'social-app-with-firebase-63a46',
    storageBucket: 'social-app-with-firebase-63a46.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMjF2-Ahr0HQudFDjTDhxZVQP51dELX_0',
    appId: '1:932125453091:ios:f31ecbbf9b22f869083a96',
    messagingSenderId: '932125453091',
    projectId: 'social-app-with-firebase-63a46',
    storageBucket: 'social-app-with-firebase-63a46.appspot.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
